baseURL: http://example.org/
languageCode: en-us
title: MML
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Search
          url: search/
          weight: 1
        - name: People
          url: people/
          weight: 5
        - name: Publications
          url: publications/
          weight: 5
        - name: Codes
          url: codes/
          weight: 10
        - name: Tags
          url: tags/
          weight: 15
        - name: Archive
          url: archives/
          weight: 20

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "The Macromolecular Materials Laboratory (MML) is an association of research groups within the Department of Materials Science at Cambridge University."
  author: CJ
  defaultTheme: auto
  disableThemeToggle: false
  ShowShareButtons: false
  ShowReadingTime: true
  disableSpecial1stPost: false
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: false
  comments: false

  homeInfoParams:
    Title: "The Macromolecular Materials Laboratory"
    Content: >
      Welcome to the Macromolecular Materials Laboratory's (MML) website.
  socialIcons:
    - name: github
      url: "https://github.com/ConorWilliams"
    - name: LinkedIn
      url: "https://www.linkedin.com/company/the-macromolecular-materials-lab/"
    - name: Rss
      url: "index.xml"

  editPost:
    URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  assets:
    disableHLJS: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
